name = "redraw_dom"
target = "javascript"
version = "19.1.1"

description = "Redraw DOM renderer. Take a look at Redraw to use it."
licences = ["MIT"]
gleam = ">= 1.12.0"

[[links]]
title = "Sponsor"
href = "https://github.com/sponsors/ghivert"

[repository]
type = "github"
user = "ghivert"
repo = "redraw"
path = "redraw_dom"

[dependencies]
gleam_fetch = ">= 1.3.0 and < 2.0.0"
gleam_stdlib = ">= 0.51.0 and < 2.0.0"
redraw = ">= 19.0.0 and < 20.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
